### ISSUE TITLE
document updating code-server

### ISSUE THREAD

**Issue by bpmct** [cdr/deploy-code-server#13]
Railway seems to aggressively cache the :latest tag

see https://github.com/cdr/code-server/discussions/2902#discussioncomment-491313

**Comment by jsjoeio** [comment]
Came here to ask the same thing! Looks like I'll have to put it manually like you suggested.

**Comment by jsjoeio** [comment]
Asked again here: https://github.com/cdr/code-server/discussions/3075#discussioncomment-607698

**Comment by bpmct** [comment]
thanks joe. I'll be working on it this week
