### ISSUE TITLE
[Question] How to Update

### ISSUE THREAD

**Issue by Lukas-Batema** [cdr/deploy-code-server#15]
So, I am using this method of using this application, and it seems to me that although it gives notification of a new release is out, it doe not have the ability to update. If I am missing something, please tell me how to update to the most recent version. Thanks!

**Comment by bpmct** [comment]
Hi @Lukas-Batema - some providers, such as railway will aggressively "cache" the code-server image, so it won't update to the latest. I will fix this in #13.

In the meantime, you can edit the Dockerfile in your repo and change from

`FROM code-server:latest`
to 
`FROM codercom/code-server:3.9.2`

**Comment by Lukas-Batema** [comment]
> Hi @Lukas-Batema - some providers, such as railway will aggressively "cache" the code-server image, so it won't update to the latest. I will fix this in #13.
> 
> 
> 
> In the meantime, you can edit the Dockerfile in your repo and change from
> 
> 
> 
> `FROM code-server:latest`
> 
> to 
> 
> `FROM codercom/code-server:3.9.2`

Ok, thanks. It worked when I updated the docker file (I use railway).

**Comment by bpmct** [comment]
closing in favor of #13
