### ISSUE TITLE
Push and pull from separate google drive subdirectories using rclone

### ISSUE THREAD

**Issue by tmprk** [cdr/deploy-code-server#24]
I'm using heroku, so I need to use rclone and am using google drive as remote. In my google drive, I set a root folder to push and pull from. But whenever I start the container, it auto-pulls _everything_ in that folder. But what if I wanted to

1. open a blank project in code-server
2. assign its remote to a new subdirectory in said root folder
3. push changes and then be able to do the same thing for other projects

that way, if I start up the instance, I can selectively pull from any subdirectory (which are the projects) and then push to them as well. This would be more organized and efficient instead of pulling the entire folder. I'm sure there's a way to do this but couldn't find much in the rclone documentation.

Besides that, my experience using code-server has been really positive so far and as a student, heroku + rclone comes in handy too. Thanks for the detailed setup guide!

**Comment by AurangAsif** [comment]
To stop auto-pulling from rclone, you can set the `RCLONE_AUTO_PULL` env var to false (it has a default value of true). As for sub directories, if you set an id for a root folder when configuring rclone, then you can use the `RCLONE_DESTINATION` env var, Setting it to `/` will sync everything in the folder. Setting it to something like `project1` will create a folder inside the gdrive folder and sync everything into and out of there.

To see a full list of env vars, check out https://github.com/cdr/deploy-code-server/tree/main/deploy-container.

**Comment by AurangAsif** [comment]
> Thanks for the reply. So you would have to change the destination manually in the env variables every time, correct? Like, you can't change it from terminal once you're in a code-server session.

You could change the env vars everytime, or manually run rclone commands. Or just make a shell script with the following contents and run it everytime you change the destination. Copied from the entrypoint.sh script.
```shell
RCLONE_REMOTE_PATH=${RCLONE_REMOTE_NAME:-code-server-remote}:${RCLONE_DESTINATION:-code-server-files}
echo "rclone sync $RCLONE_FLAGS $RCLONE_SOURCE_PATH $RCLONE_REMOTE_PATH -vv" > /home/coder/push_remote.sh
echo "rclone sync $RCLONE_FLAGS $RCLONE_REMOTE_PATH $RCLONE_SOURCE_PATH -vv" > /home/coder/pull_remote.sh
```

**Comment by tmprk** [comment]
Thanks. I ended up putting shell script in the .vscode directory in `/home/coder/project`, and I replaced `-code-server-files` with the name of the new project directory in google drive. `RCLONE_SOURCE_PATH=${RCLONE_SOURCE:-$START_DIR}` is also required for the last two commands.

**Comment by bpmct** [comment]
Thanks. I ended up putting shell script in the .vscode directory in /home/coder/project, and I replaced -code-server-files with the name of the new project directory in google drive.

I'm not sure I'm following. Wouldn't this be solved if you just specified a unique `RCLONE_DESTINATION` environment variable when creating it? This would send each project to a unique google drive folder.

Do you need to edit the location after the fact?

**Comment by tmprk** [comment]
Yeah, I was trying to find a way to change the destination after opening code-server. Instead of changing the Env variables beforehand. I put it in the .vscode directory because I am pulling from an empty base project (that has .vscode) to set the theme from settings.json every time, but I should really just make the shell script in entrypoint.sh...

Apart from the shell script, is there a better way to do this?

**Comment by bpmct** [comment]
> Instead of changing the Env variables beforehand. 

if you change the env variables after you open vs code, it will rebuild the workspace

**Comment by tmprk** [comment]
I run this inside vscode and specify the new destination as an argument. After pushing, everything seems to be fine. Am I doing something wrong? Sorry, I didn't mean to say I was changing the env variables, only `push_remote.sh` and `pull_remote.sh`.

```shell
RCLONE_SOURCE_PATH=${RCLONE_SOURCE:-$START_DIR}
RCLONE_REMOTE_PATH=${RCLONE_REMOTE_NAME:-code-server-remote}:${RCLONE_DESTINATION:-$1}

echo "rclone sync $RCLONE_SOURCE_PATH $RCLONE_REMOTE_PATH -vv" > /home/coder/push_remote.sh
echo "rclone sync $RCLONE_REMOTE_PATH $RCLONE_SOURCE_PATH -vv" > /home/coder/pull_remote.sh
```

**Comment by bpmct** [comment]
Totally not doing anything wrong at all! I was mainly confused what it was doing differently from setting the env variable beforehand. In railway itself, you can set the variables after you first deploy it, and then it would redeploy with that variable configured in the environment.

However, passing it as an argument gives you more control.

**Comment by tmprk** [comment]
I made some small [edits](https://github.com/tmprk/code-server/blob/0fd9812091a8b8f960d407af30101c4a21412818/deploy-container/entrypoint.sh#L51-L56) to entrypoint.sh. It should be a bit more clear now. So if I'm in the middle of one project, I can run `./push-and-pull-from.sh [project name]` and it will let me set a new destination to push to (probably have to delete any current unrelated files before I push). But I will look into Railway as you said. Thanks!

**Comment by bpmct** [comment]
Sweet! So I will definitely implement this, and it will go like
1. check if argument ($1 exists)
2. if not, use $RAILWAY_DESTINATION (if exists)
3. if not, use "code-server-remote" (if exists)

**Comment by tmprk** [comment]
Wait, sorry if I'm misunderstanding. But when would these 3 occur? I thought the argument is something that is given to change the rclone destination _after_ you open code-server, not during entry point of the container.

**Comment by bpmct** [comment]
`RAILWAY_DESTINATION` would just be the name of the single folder that it goes to. 

Yeah I would probably rewrite the push_remote and pull_remote to take in arguments, like yours does

**Comment by bpmct** [comment]
closing because i believe this use case is more centered around supporting multiple remotes
