### ISSUE TITLE
how $password var is used

### ISSUE THREAD

**Issue by nileio** [cdr/deploy-code-server#27]
can someone help me understand how do you pass $password to code-server build? will $password var be logged anywhere in cleartext? I refer to container deployment with railway
thanks

**Comment by bpmct** [comment]
@nileio This is done as an [environment variable](https://medium.com/chingu/an-introduction-to-environment-variables-and-how-to-use-them-f602f66d15fa) in the container. It would be accessible for anyone who has access to the shell. 

Railway shows how to manage them here: https://docs.railway.app/environments

They are stored in plaintext, but can only be seen by anyone with shell access to the container (you would get shell access if you log in successfully to code-server or Railway). If you don't want it to be cleartext, you can use the `HASHED_PASSWORD` variable and set the SHA-256 hash of password

**Comment by nileio** [comment]
@bpmct thank you
