### ISSUE TITLE
Haxe doesnt work very well

### ISSUE THREAD

**Issue by crispyi2** [cdr/deploy-code-server#28]
### secifically HaxeFlixel, OpenFL, and Lime
---
### ⬇️  Here are the links to the websites ⬇️ 
Haxe ‎‏‏‎ ‎‎‏‏‎ ‎Haxeflixel‎‏‏‎ ‎‎‏‏‎ ‎‎‏‏‎ ‎OpenFL‎‏‏‎ ‎‏‏‎‎‎‏‏‎ ‎‎‏‏‎ ‎Lime
‎‏‏‎ ‎‏‏‎‎‏‏‎ ‎‏‏‎[<img src="https://avatars.githubusercontent.com/u/3826779?s=200&v=4" width="30"/>](https://haxe.org/)‎‎‎‎‎ ‏‏‎ ‎‏‎‏‏‎ ‎‏‏‎ ‎‏‏‎‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎‏‏‎ ‎ [<img src="https://avatars.githubusercontent.com/u/4309553?s=200&v=4" width="30" style=""/>](https://haxeflixel.com/)  ‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎‎‏‏‎ ‎‏‏‎‎‏‏‎ ‎‏‏‎‎‏‏‎‏‏‎ ‎‏‏‎‎‏‏‎‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎‏‏‎ ‏‏‎  [<img src="https://avatars.githubusercontent.com/u/4061208?s=200&v=4" width="30" style=""/>](https://www.openfl.org/)  ‎‏‏‎ ‎‏‏‎ ‎‏‏‎‎‏‏‎ ‎‏‏‎‎‏‏ ‎‏‏‎ ‎‏‏‎‎‏‏‎ ‎‏‏‎ ‎‏‏‎ ‎‏‏‎[<img src="https://avatars.githubusercontent.com/u/57459256?s=200&v=4" width="30" style=""/>](https://lime.software/)
---
When I test my haxeflixel game using 
`lime test html5`
it did everything it was supposed to do, it built the game and opened up a server on port 3000 with the game loaden up on it so i could test it

only problem was that it didn't serve any of the content except for the .html file it generated even though it was also supposed to serve a .html file a .png file and .js file.

so i got a console error that said this

```
❌ Failed to load resource: the server responded with a status of 500 ()   4K-Engine.js:1

❌ Uncaught ReferenceError: lime is not defined                            3000:94
     at 3000:94

❌ Failed to load resource: the server responded with a status of 500 ()   favicon.png:1
```

## The .js file
So what this means is it didn't serve the .js file which whas this one 4K-Engine.js
### Note: (4K-Engine is the name of the game im developing btw) [here is a link to the github repo for my game](https://github.com/crispyi2/4K-Engine) ⏪⏪⏪ clone it if you want to reproduce it which i will explain how to do in a second
the .js file is what had everything the game needed to run

the .html file was the only thing that was actually served but its really useless without the 4K-Engine.js file here is why

🔽 this part 🔽 
```
❌ Uncaught ReferenceError: lime is not defined                            3000:94
     at 3000:94
```
is whining about some javascript code automatically embedded in the html tag
🔽 here is the script tag im talking about 🔽 
```
<script type="text/javascript">
	lime.embed ("4K-Engine", "openfl-content", 1280, 720, { parameters: {} });
</script>
```

Lime was defined in the 4K-Engine.js file but again the 4K-Engine.js file wasn't served
(Btw Lime is what is reccomended to build haxeflixel projects with)
and if you couldnt tell already lime is also used to embed the content into the webpage

## The .png file

I dont really care about the fucking favicon logo since I don't really need it to load the game

## reproducing the bug

Here is how you reproduce the bug

Open the games folder in code server so that it is the root directory

Open the integrated terminal

1 type this to automatically build and run a server withe the game loaded on it
`lime test html5` (also it has to be this command)

2 then go to this url
`url.codeserver.is.being.hosted.on/proxy/3000`

3 open up the developer console (this is done differently with every web browser)
- in google chrome you press `Ctrl+Shift+I`
    - then click the console tab
- in firefox there is two ways
    - you can click Browser Console in the Web Developer sub menu
    - or you can press `Ctrl+Shift+J on your keyboard
- idk how to do it on opera
## btw

the only reason im not submitting this isuue on lime's github repo is because i haven't had this problem with any other web based ides like Gitpod and GoormIde and iv'e also had similar problems with other programming languages like java (also java is a bad example cuz of how ancient and hard to work with it is but it was the first example that came to mind so yeah) and even ad a similar problem when testing a vscode extension im developing which ill post an issue for in a few days cuz writing details issues is really time consuming so umm yeah

---

# btw again

### Info

- Operating System: ChromeOS
    - System Version: 89.0.4389.130 (Official Build) (64-bit)
- Code Server Host: [Railway](railway.app)
- Code Server Version: 3.9.3
    - Vscode Version: 1.54.2

**Comment by bpmct** [comment]
Thanks for reporting. I'll check this out today!

**Comment by crispyi2** [comment]
I Figured out why it was doing this. I didnt type `/` at the end of `host.com/proxy/<port>` so for some reason that made it not wanna serve it
