### ISSUE TITLE
Heroku: Build failed due to an error: Timed out compiling app. After installing language dependencies and environment for this Code Server.

### ISSUE THREAD

**Issue by BingoKingo** [cdr/deploy-code-server#29]

**Comment by bpmct** [comment]
Hey! This is all done in the Dockerfile in the repo you cloned

https://github.com/cdr/deploy-code-server/blob/main/Dockerfile#L22-L35

You will have to install the dependencies there with `RUN` and `ENV` commands.

**Comment by BingoKingo** [comment]
I would like to use the wget command to install packages, so where to put these dependencies files?

**Comment by bpmct** [comment]
So within the Dockerfile, you would do something like
```sh
RUN wget [url]
RUN # any other command here
```

see this for help: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by bpmct** [comment]
@BingoKingo saw you reopened. Can you add more details?

**Comment by BingoKingo** [comment]
It still deploying after I installed dependencies on Railway.
`Successfully built 2a684eff0f5e`
`Successfully tagged 10.138.0.45:5005/04b986c4-902c-4a9e-9197-3f2a8e71c756:latest `

**Comment by bpmct** [comment]
this may be a railway bug? if there are no errors, I would try manually deploying again or pushing another commit to the repo.

Let me know if that helps

**Comment by BingoKingo** [comment]
All deployments are deploying... I could not figure out the reason.

**Comment by BingoKingo** [comment]
After deploying on Heroku, I have found that problem:
 `=!= Build failed due to an error:
=!= Timed out compiling app`
