### ISSUE TITLE
how to change work dir 

### ISSUE THREAD

**Issue by bnsave100** [cdr/deploy-code-server#31]
so i want to put all my git clones files in one single dir 
should I add this in the **# Install stuff u want** or replace here in **# Fix permissions for code-server**
```
RUN mkdir -m 777 'work'
RUN chmod +x 'work'
RUN %cd 'work'
```

**Comment by bpmct** [comment]
So currently, the container will auto clone 1 project into a work dir. This currently defaults to `/home/coder/project`.

You can change the directory by changing the `START_DIR` environment variable, and I believe it will actually make the folder for you.

If you want to clone multiple repos in there, you can omit the `GIT_REPO` environment variable and then you can install whatever you want in there.
