### ISSUE TITLE
Zeet + Heroku integration

### ISSUE THREAD

**Issue by sinnrrr** [cdr/deploy-code-server#32]
Hey guys! I appreciate all the work you've done on `code-server` and `deploy-code-server`, really fantastic. In case you want to support more platforms to deploy, I have done an integration with [Zeet](https://zeet.co/) and [Heroku](https://heroku.com/) (you have it too). In case you want to use it: [here is the link to repo](https://github.com/sinnrrr/videil)

I'm constantly updating it to support more platforms.
Best regards.

**Comment by bpmct** [comment]
Hi @sinnrrr!

Thanks for submitting. I tried launching the project in Zeet with the link in your repo, but ran into errors. When I deployed the `bencdr/code-server-deploy-container`, it worked though.

I would love to document the Zeet install, but I noticed it looked like you were working on a larger project. What is your end goal with this?

Ben

**Comment by sinnrrr** [comment]
yeah, seems like it's not working (Zeet is uzing `herokuish`, so, maybe, the problem is on their side)

the purpose of this project was the ability to deploy `code-server` (it was created before `deploy-code-server`)

your deployment method is better, so I'll just archive the project
sorry for bothering

**Comment by bpmct** [comment]
no worries, thanks for feedback. I opened another issue to document zeet specifically
