### ISSUE TITLE
Is it possible to use it with Firebase?

### ISSUE THREAD

**Issue by AyaanZaveri** [cdr/deploy-code-server#39]

**Comment by bpmct** [comment]
I haven't looked into this yet, but it might be possible to use a firebase app with the container + block storage. I will explore

**Comment by AyaanZaveri** [comment]
If this does work it would be great because Firebase runs on Google Servers, which means everything would run smooth!

**Comment by AyaanZaveri** [comment]
What about netlify?

**Comment by bpmct** [comment]
Netlify, to my knowledge, can't deploy Docker-based applications, only node/static sites. May be wrong though

**Comment by AyaanZaveri** [comment]
Oh, so code-server isn't a static site?

**Comment by bpmct** [comment]
Nope.

**Comment by bpmct** [comment]
Nope, code-server includes a full backend and express routes

**Comment by bpmct** [comment]
With some further digging you can't really use deploy-code-server directly with firebase, but you could deploy the container to cloud run: https://firebase.google.com/docs/hosting/cloud-run

deploy-container docs: https://github.com/cdr/deploy-code-server/tree/main/deploy-container

**Comment by AyaanZaveri** [comment]
Would that be free?

**Comment by bpmct** [comment]
It likely would be, but depends on your workload: https://cloud.google.com/run/pricing
