### ISSUE TITLE
How to add any var which don't need to fill can be skipped ?

### ISSUE THREAD

**Issue by Rishisuperyo-Op** [cdr/deploy-code-server#56]
How to add any var which don't need to fill can be skipped ?

**Comment by Rishisuperyo-Op** [comment]
#How to add any var which don't need to fill can be skipped ?

**Comment by bpmct** [comment]
Not sure I understand the question @Rishisuperyo-Op? You can specify environment variables in the dockerfile as so:

```Dockerfile
# Dockerfile

# ... stuff 
ENV MY_VAR my-value
#... stuff
```

**Comment by Rishisuperyo-Op** [comment]
Yes is this will make my deploy project as heroku ,like in app.json we can set the var requirements to false or true can we also in railway, is there any way I just want to know cause I am launching a big project for telegram userbot.

**Comment by bpmct** [comment]
Yeah, Railway and Heroku both support enabling/disabling vars on creation. If you remove them, you can set them by default in the dockerfile:

See these config files:

Heroku: 
https://github.com/cdr/deploy-code-server/blob/main/app.json#L13-L22

Railway (it is done in the link):
https://github.com/cdr/deploy-code-server/blame/main/guides/railway.md#L11

**Comment by Rishisuperyo-Op** [comment]
Thanks sir :)

**Comment by Rishisuperyo-Op** [comment]
Thank u very much :)
